# Generated by Django 5.0.6 on 2024-05-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.CharField(max_length=255)),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name="Streams",
            new_name="Tournament",
        ),
        migrations.AddField(
            model_name="channel",
            name="url",
            field=models.URLField(max_length=255, null=True),
        ),
    ]
