# Generated by Django 5.0.6 on 2024-05-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0005_channel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
