# Generated by Django 5.0.6 on 2024-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0006_alter_feedback_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"ordering": ["channel_name"]},
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="country",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="stream_name",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_name",
            field=models.CharField(max_length=255),
        ),
    ]
