# Generated by Django 5.0.6 on 2024-05-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0007_alter_channel_options_remove_tournament_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
    ]
