# Generated by Django 5.0.6 on 2024-05-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0008_playlist_delete_tournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="country",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="owners",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="website",
        ),
    ]
