# Generated by Django 5.0.6 on 2024-05-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "peru_api",
            "0009_remove_channel_country_remove_channel_lang_and_more",
        ),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="channel",
        #     name="playlist",
        #     field=models.ForeignKey(
        #         default="",
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="peru_api.playlist",
        #     ),
        # ),
    ]
