# Generated by Django 5.0.6 on 2024-05-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0010_channel_playlist"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="channel",
        #     name="playlist",
        #     field=models.ForeignKey(
        #         default=models.SET(1),
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="peru_api.playlist",
        #     ),
        # ),
    ]
