# Generated by Django 5.0.6 on 2024-05-17 19:21

import django.db.models.deletion
import peru_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0011_alter_channel_playlist"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="channel",
        #     name="playlist",
        #     field=models.ForeignKey(
        #         default=peru_api.models.get_or_create_playlist,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="peru_api.playlist",
        #     ),
        # ),
    ]
