# Generated by Django 5.0.6 on 2024-05-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0012_alter_channel_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peru_api.playlist",
            ),
        ),
    ]
