# Generated by Django 5.0.6 on 2024-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peru_api", "0013_channel_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
